import type { Localized } from "./i18n";

// Interface copy (navigation, labels, buttons) in both languages.
// Profile and case study copy live in their own content files.
export const ui = {
  en: {
    skip: "Skip to content",
    nav: { home: "Home", work: "Work", about: "About", contact: "Contact", label: "Main", menu: "Menu", close: "Close menu" },
    language: { switchTo: "Español", short: "ES", label: "Ver el sitio en español" },
    footer: { together: "Let's work together" },
    hero: {
      lines: ["Product", "Designer", "& builder"],
      tail: "Landing pages, admin panels and MVPs, built with Claude Code.",
      seeWork: "See my work",
      aboutMe: "About me",
      hint: "Move your cursor to smear the light.",
    },
    home: { selectedWork: "Selected work" },
    work: {
      eyebrow: "Work",
      title: "Case studies",
      intro: "How I decided what to build, what I designed, and what changed after it shipped.",
      metaTitle: "Work",
      metaDescription: "Case studies: product decisions, process and results.",
      projects: "Projects",
    },
    case: {
      sections: ["At a glance", "The problem", "What I found", "Decisions", "Results"],
      sectionsLabel: "Case study sections",
      glance: { problem: "The problem", whatIDid: "What I did", result: "The result" },
      decision: "Decision",
      before: "Before",
      after: "After",
      illustration: "Illustrative panel UI with sample data.",
      illustrationLabel: "Illustration of the lead panel: a list of leads with source, status and landing page actions",
      mock: { lead: "Lead", source: "Source", status: "Status", landing: "Landing", leadName: "Lead name", form: "Contact form", manual: "Manual entry", fresh: "New", ready: "Landing ready", generate: "Generate", view: "View" },
      nextCase: "Next case",
      moreWork: "More work",
      allCases: "All case studies",
      moreWorkLabel: "More work",
    },
    about: {
      eyebrow: "About",
      metaTitle: "About",
      metaDescription: "Product Designer with 6+ years of experience across brand, web and mobile products.",
      background: "Background",
      blocks: { strengths: "What I do best", process: "How I work", tools: "Tools", experience: "Experience" },
      step: "Step",
      cta: { title: "Have a product to design or build?", body: "Open to product designer roles and freelance projects.", button: "Get in touch" },
    },
    contact: {
      eyebrow: "Contact",
      metaTitle: "Contact",
      metaDescription: "Get in touch about a product designer role or a freelance project.",
      title: "Let's build something worth using",
      intro: "Email is the fastest way to reach me. Tell me what you're working on.",
      emailLabel: "Email",
      pathsLabel: "What are you looking for?",
      copy: "Copy email",
      copied: "Copied",
      paths: [
        {
          eyebrow: "Hiring",
          title: "A product designer for your team",
          body: "I'm open to product designer roles. I can walk you through more of my work on a call.",
          subject: "Product designer role",
          cta: "Write about a role",
        },
        {
          eyebrow: "Freelance",
          title: "A landing page, admin panel or MVP",
          body: "I design and build it with Claude Code, from scope to a working product.",
          subject: "Freelance project",
          cta: "Tell me about your project",
        },
      ],
    },
    notFound: { title: "This page doesn't exist", body: "The link may be old or mistyped.", back: "Back to home" },
  },
  es: {
    skip: "Saltar al contenido",
    nav: { home: "Inicio", work: "Proyectos", about: "Sobre mí", contact: "Contacto", label: "Principal", menu: "Menú", close: "Cerrar menú" },
    language: { switchTo: "English", short: "EN", label: "View the site in English" },
    footer: { together: "Trabajemos juntos" },
    hero: {
      lines: ["Diseñador", "de producto", "que construye"],
      tail: "Landing pages, paneles de administración y MVPs, construidos con Claude Code.",
      seeWork: "Ver mi trabajo",
      aboutMe: "Sobre mí",
      hint: "Mueve el cursor para arrastrar la luz.",
    },
    home: { selectedWork: "Proyectos destacados" },
    work: {
      eyebrow: "Proyectos",
      title: "Casos de estudio",
      intro: "Cómo decidí qué construir, qué diseñé y qué cambió después del lanzamiento.",
      metaTitle: "Proyectos",
      metaDescription: "Casos de estudio: decisiones de producto, proceso y resultados.",
      projects: "Proyectos",
    },
    case: {
      sections: ["De un vistazo", "El problema", "Lo que encontré", "Decisiones", "Resultados"],
      sectionsLabel: "Secciones del caso de estudio",
      glance: { problem: "El problema", whatIDid: "Qué hice", result: "El resultado" },
      decision: "Decisión",
      before: "Antes",
      after: "Después",
      illustration: "Interfaz ilustrativa del panel con datos de ejemplo.",
      illustrationLabel: "Ilustración del panel de leads: una lista de leads con origen, estado y acciones de landing",
      mock: { lead: "Lead", source: "Origen", status: "Estado", landing: "Landing", leadName: "Nombre del lead", form: "Formulario", manual: "Carga manual", fresh: "Nuevo", ready: "Landing lista", generate: "Generar", view: "Ver" },
      nextCase: "Siguiente caso",
      moreWork: "Más proyectos",
      allCases: "Todos los casos de estudio",
      moreWorkLabel: "Más proyectos",
    },
    about: {
      eyebrow: "Sobre mí",
      metaTitle: "Sobre mí",
      metaDescription: "Product Designer con más de 6 años de experiencia en marca, productos web y móviles.",
      background: "Trayectoria",
      blocks: { strengths: "Lo que mejor hago", process: "Cómo trabajo", tools: "Herramientas", experience: "Experiencia" },
      step: "Paso",
      cta: { title: "¿Tienes un producto para diseñar o construir?", body: "Abierto a roles de product designer y a proyectos freelance.", button: "Hablemos" },
    },
    contact: {
      eyebrow: "Contacto",
      metaTitle: "Contacto",
      metaDescription: "Escríbeme por un rol de product designer o un proyecto freelance.",
      title: "Construyamos algo que valga la pena usar",
      intro: "El email es la forma más rápida de contactarme. Cuéntame en qué estás trabajando.",
      emailLabel: "Email",
      pathsLabel: "¿Qué estás buscando?",
      copy: "Copiar email",
      copied: "Copiado",
      paths: [
        {
          eyebrow: "Contratación",
          title: "Un product designer para tu equipo",
          body: "Estoy abierto a roles de product designer. Puedo mostrarte más de mi trabajo en una llamada.",
          subject: "Rol de product designer",
          cta: "Escribir sobre un rol",
        },
        {
          eyebrow: "Freelance",
          title: "Una landing page, un panel de administración o un MVP",
          body: "Lo diseño y lo construyo con Claude Code, desde el alcance hasta un producto funcionando.",
          subject: "Proyecto freelance",
          cta: "Contarme tu proyecto",
        },
      ],
    },
    notFound: { title: "Esta página no existe", body: "Puede que el enlace sea viejo o tenga un error.", back: "Volver al inicio" },
  },
} satisfies Localized<unknown>;

export type Ui = (typeof ui)["en"];
